MODEL:
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss", "DiceLoss"]]
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  # non-overlap regularization
  REGU_OPT: ["Nonoverlap"]
  REGU_TARGET: [[0]]
  REGU_WEIGHT: [4.0]
DATASET:
  OUTPUT_PATH: outputs/JWR15_Syn_BCE_DICE_Regu/
