MODEL:
  ARCHITECTURE: superhuman_iso_con
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss"]]
  LOSS_WEIGHT: [[1.0]]
  WEIGHT_OPT: [["1"]]
  OUTPUT_ACT: [["none"]]
  OUT_PLANES: 2

DATASET:
  OUTPUT_PATH: outputs/Synapse-BCE-r_3_2_superhuman_iso/

INFERENCE:
  OUTPUT_PATH: outputs/Synapse-BCE-r_3_2_superhuman_iso/test