MODEL:
  ARCHITECTURE: RSUNet
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss"]]
  LOSS_WEIGHT: [[1.0]]
  WEIGHT_OPT: [["1"]]
  OUTPUT_ACT: [["none"]]
  OUT_PLANES: 2

DATASET:
  OUTPUT_PATH: outputs/Synapse-BCE-r_3_2_chang/

INFERENCE:
  OUTPUT_ACT: ["none"]
  OUTPUT_PATH: outputs/Synapse-BCE-r_3_2_chang/test