MODEL:
  ARCHITECTURE: superhuman_aniso
  LOSS_OPTION: [["WeightedBCE"]]
  LOSS_WEIGHT: [[1.0]]
  WEIGHT_OPT: [["1"]]
  OUTPUT_ACT: [["none"]]

DATASET:
  OUTPUT_PATH: outputs/Synapse-BCE-r_3_2_superhuman_iso/

INFERENCE:
  OUTPUT_PATH: outputs/Synapse-BCE-r_3_2_superhuman_iso/test