MODEL:
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss"]]
  LOSS_WEIGHT: [[1.0]]
  WEIGHT_OPT: [["1"]]
  OUTPUT_ACT: [["none"]]

DATASET:
  INPUT_PATH: /braindat/lab/qic/challenge/synapse_detection/data/training_set_new/
  IMAGE_NAME:
    - train_sample3_vol0/img.tif
    - train_sample3_vol1/img.tif
    - train_sample3_vol2/img.tif
    - train_sample3_vol3/img.tif
    - train_sample3_vol4/img.tif
  LABEL_NAME:
    - train_sample3_vol0/gt_r1_0.tif
    - train_sample3_vol1/gt_r1_0.tif
    - train_sample3_vol2/gt_r1_0.tif
    - train_sample3_vol3/gt_r1_0.tif
    - train_sample3_vol4/gt_r1_0.tif
  OUTPUT_PATH: outputs/Synapse-BCE-r_1_0_v2/
  REJECT_SAMPLING:
    SIZE_THRES: 20
    P: 0.95
INFERENCE:
  OUTPUT_PATH: outputs/Synapse-BCE-r_1_0_v2/test
SOLVER:
  ITERATION_TOTAL: 200000